/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sound.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sound.pb-c.h"
void   soundwave__sound_wave__sample__init
                     (Soundwave__SoundWave__Sample         *message)
{
  static const Soundwave__SoundWave__Sample init_value = SOUNDWAVE__SOUND_WAVE__SAMPLE__INIT;
  *message = init_value;
}
void   soundwave__sound_wave__init
                     (Soundwave__SoundWave         *message)
{
  static const Soundwave__SoundWave init_value = SOUNDWAVE__SOUND_WAVE__INIT;
  *message = init_value;
}
size_t soundwave__sound_wave__get_packed_size
                     (const Soundwave__SoundWave *message)
{
  assert(message->base.descriptor == &soundwave__sound_wave__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t soundwave__sound_wave__pack
                     (const Soundwave__SoundWave *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &soundwave__sound_wave__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t soundwave__sound_wave__pack_to_buffer
                     (const Soundwave__SoundWave *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &soundwave__sound_wave__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Soundwave__SoundWave *
       soundwave__sound_wave__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Soundwave__SoundWave *)
     protobuf_c_message_unpack (&soundwave__sound_wave__descriptor,
                                allocator, len, data);
}
void   soundwave__sound_wave__free_unpacked
                     (Soundwave__SoundWave *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &soundwave__sound_wave__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor soundwave__sound_wave__sample__field_descriptors[2] =
{
  {
    "first",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Soundwave__SoundWave__Sample, first),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "second",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Soundwave__SoundWave__Sample, second),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned soundwave__sound_wave__sample__field_indices_by_name[] = {
  0,   /* field[0] = first */
  1,   /* field[1] = second */
};
static const ProtobufCIntRange soundwave__sound_wave__sample__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor soundwave__sound_wave__sample__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "soundwave.SoundWave.Sample",
  "Sample",
  "Soundwave__SoundWave__Sample",
  "soundwave",
  sizeof(Soundwave__SoundWave__Sample),
  2,
  soundwave__sound_wave__sample__field_descriptors,
  soundwave__sound_wave__sample__field_indices_by_name,
  1,  soundwave__sound_wave__sample__number_ranges,
  (ProtobufCMessageInit) soundwave__sound_wave__sample__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor soundwave__sound_wave__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Soundwave__SoundWave, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "samples",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Soundwave__SoundWave, n_samples),
    offsetof(Soundwave__SoundWave, samples),
    &soundwave__sound_wave__sample__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned soundwave__sound_wave__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = samples */
};
static const ProtobufCIntRange soundwave__sound_wave__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor soundwave__sound_wave__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "soundwave.SoundWave",
  "SoundWave",
  "Soundwave__SoundWave",
  "soundwave",
  sizeof(Soundwave__SoundWave),
  2,
  soundwave__sound_wave__field_descriptors,
  soundwave__sound_wave__field_indices_by_name,
  2,  soundwave__sound_wave__number_ranges,
  (ProtobufCMessageInit) soundwave__sound_wave__init,
  NULL,NULL,NULL    /* reserved[123] */
};
