# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sound.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sound.proto',
  package='soundwave',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0bsound.proto\x12\tsoundwave\"p\n\tSoundWave\x12\x0c\n\x04name\x18\x01 \x02(\t\x12,\n\x07samples\x18\x04 \x03(\x0b\x32\x1b.soundwave.SoundWave.Sample\x1a\'\n\x06Sample\x12\r\n\x05\x66irst\x18\x01 \x02(\x01\x12\x0e\n\x06second\x18\x02 \x02(\x01'
)




_SOUNDWAVE_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='soundwave.SoundWave.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first', full_name='soundwave.SoundWave.Sample.first', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='second', full_name='soundwave.SoundWave.Sample.second', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=138,
)

_SOUNDWAVE = _descriptor.Descriptor(
  name='SoundWave',
  full_name='soundwave.SoundWave',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='soundwave.SoundWave.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='samples', full_name='soundwave.SoundWave.samples', index=1,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SOUNDWAVE_SAMPLE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=138,
)

_SOUNDWAVE_SAMPLE.containing_type = _SOUNDWAVE
_SOUNDWAVE.fields_by_name['samples'].message_type = _SOUNDWAVE_SAMPLE
DESCRIPTOR.message_types_by_name['SoundWave'] = _SOUNDWAVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SoundWave = _reflection.GeneratedProtocolMessageType('SoundWave', (_message.Message,), {

  'Sample' : _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), {
    'DESCRIPTOR' : _SOUNDWAVE_SAMPLE,
    '__module__' : 'sound_pb2'
    # @@protoc_insertion_point(class_scope:soundwave.SoundWave.Sample)
    })
  ,
  'DESCRIPTOR' : _SOUNDWAVE,
  '__module__' : 'sound_pb2'
  # @@protoc_insertion_point(class_scope:soundwave.SoundWave)
  })
_sym_db.RegisterMessage(SoundWave)
_sym_db.RegisterMessage(SoundWave.Sample)


# @@protoc_insertion_point(module_scope)
